SET ECHO ON
CREATE OR ALTER FUNCTION GETCLIENTNAME (nomClient IN VARCHAR) RETURN VARCHAR
IS
nomClient VARCHAR;
BEGIN
SELECT * INTO tp1TestClient FROM tp1Client WHERE pClient = 1;
RETURN nomClient;
END GETCLIENTNAME;
/
